project:
  type: website
  output-dir: docs

website:
  title: "LS4003 R programming"
  page-navigation: true
  bread-crumbs: false  
  navbar:
    left:
      - text: "Why R"
        href: index.qmd
      - text: "Set Up"
        href: setup.qmd
      - text: "Learn"
        href: learn.qmd
      - text: "Careers"
        href: careers.qmd
      # - text: "CheatSheet"
      #   href: cheatsheet.qmd
      - text: "Help"
        href: help.qmd
  sidebar:
    - title: "Learn"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - section: "**R introduction: basics to graphs**"
          contents:
            - section: "R basics"
              contents:
                - href: learn.qmd
                - href: worksheets/Variables.qmd
                - href: worksheets/Comments.qmd
                - href: worksheets/ErrorMsg.qmd
                - href: worksheets/Vectors.qmd
                - href: worksheets/RFunctions.qmd
            - section: "Make a box plot"
              contents:
                - href: worksheets/CreateDataframe.qmd
                - href: worksheets/InstallPackages.qmd
                - href: worksheets/Boxplot.qmd
                - href: worksheets/GGstyle.qmd
                - href: worksheets/Boxplot_2.qmd
            - section: "R from Excel: Locust Serotonin levels"
              contents:
                - href: worksheets/importcsv.qmd
                - href: worksheets/open_csv_in_R.qmd
                - href: worksheets/Boxplot_3_from_csv.qmd
                - href: worksheets/Discrete_continuous_scale.qmd
                - href: worksheets/Violin.qmd
                - href: worksheets/Barplot_counts.qmd
            - section: "Penguin task"
              contents:
                - href: "worksheets/penguin_introduction.qmd"
                - href: "worksheets/penguin_task1.qmd"
                - href: "worksheets/penguin_task2.qmd"
                - href: "worksheets/penguin_task3.qmd"
                - href: "worksheets/penguin_task4.qmd"
            - section: "Extension: Filtering data"
              contents:
                - href: worksheets/Filtering_data_from_table.qmd
                - href: "worksheets/penguin_extension.qmd"
                - href: "worksheets/penguin_extension_2.qmd"
        - section: "**Correlations**"
          contents: 
            - section: "Correlations using heart data"
              contents:
                - href: "worksheets/heart_data.qmd"
                - href: "worksheets/age_vs_blood_pressure.qmd"
                - href: "worksheets/using_cor_function.qmd"
                - href: "worksheets/using_cor.test_function.qmd"
                - href: "worksheets/add_pvalue_to_graph.qmd"
                - href: "worksheets/add_regression_line.qmd"
                - href: "worksheets/separate_by_sex.qmd"
                - href: "worksheets/correlelogram.qmd"
            - section: "Sleep task"
              contents: 
                - href: "worksheets/sleep_introduction.qmd"
                - href: "worksheets/sleep_task.qmd"
                - href: "worksheets/sleep_extension.qmd"
        - section: "**T-tests**"
          contents:
            - href: "worksheets/unpaired_t_test.qmd"
            - href: "worksheets/t_test_options.qmd"
            - href: "worksheets/unpaired_t_test2.qmd"
            - href: "worksheets/paired_t_test.qmd"
            - href: "worksheets/one_tailed_t_test.qmd"
            - href: "worksheets/anova.qmd"
            - href: "worksheets/pairwise_t_test.qmd"
            - href: "worksheets/t-test_extension.qmd"
        - section: "**Chi-squared and fisher**"
          contents: 
            - href: "worksheets/portuguese_students.qmd"
            - href: "worksheets/contingency_tables.qmd"
            - href: "worksheets/odds_and_risk_ratios.qmd"
            - href: "worksheets/chisquared.qmd"
            - href: "worksheets/fisher.qmd"
            - href: "worksheets/chisquared_multiple_values.qmd"
            - href: "worksheets/subset_of_values.qmd"
            - href: "worksheets/chisq_extension.qmd"

  favicon: LS4003_logo_no_text.png

format:
  live-html:
    theme:
      light: lightly
      dark: darkly
    respect-user-color-scheme: true
    css: styles.css

margin-header: |
  ![](/Logo/LS4003_logo_with_text.png)

filters:
  - /Users/lizzie/Documents/Kingston/Year_2526/LS4003/Level 4 R course book/filters/tools_tabset.lua